### ISSUE TITLE
Making App.js generic?

### ISSUE THREAD

**Issue by nilem** [bmcbride/bootleaf#13]
Hi! I started using BootLeaf, and I was wondering why museums, theaters, subways and boroughts are hard-coded in App.js? Let's say I want to use BootLeaf to show a list of hotels, this means I need to modify App.js, making it impossible to update it with your new release. Or may be there is something I didn't get right?

By the way, fantastic work : BootLeaf is a unique project and I enjoy it!

**Comment by tim-massey** [comment]
I look forward to the evolution of Bootleaf, looks like an amazing bit of starter code. Thanks!

**Comment by nilem** [comment]
"looks like an amazing bit of starter code"

It is! here is the app I did with : https://justeduneuf.ca 

I did a lot of change, but BootLeaf saved me a lot of time. I would be happy to contribute with some parts of my code.

**Comment by bmcbride** [comment]
@nilem That is awesome! Thanks so much for sharing your application. BTW, Montreal is one of my absolute favorite cities!

**Comment by tforward** [comment]
-"people want to be able to use it "out of the box"
Speaking of which, if I fork bootstrap and download to local, when open index.html the screen is pretty much black with just a bit of text. What I'm I missing? Do you need a mapbox account for this to work?

**Comment by bmcbride** [comment]
I just added protocols for script and css resources so it will load without a web server, however, the geojson will still throw cross origin errors.

**Comment by mayureshbhole** [comment]
Sir please add idea for one to many relation from database
click on one building and display info of each flat owner
i need it for my all projectd please help out

**Comment by bmcbride** [comment]
@mayureshbhole Sorry, but that is out of the scope of this simple template.
