### ISSUE TITLE
Dynamic loading of markers via AJAX based on current map view bbox

### ISSUE THREAD

**Issue by jamesinealing** [bmcbride/bootleaf#14]
I always feel guilty asking for new features on free softare, but I was wondering if you had ever thought of adding dynamic loading of markers on map move / zoom by passing bbox parameters to a public API such as Flickr? Do you think this would be hard? I'm willing to give it a try if you have any pointers.

**Comment by bmcbride** [comment]
I don't think this functionality necessarily belongs in the BootLeaf template, but here's an example of how it could be handled using the panoramio API: http://jsfiddle.net/bmcbride/4qvdz3xo/.
