### ISSUE TITLE
Typeahead search functionality with 'enter' button

### ISSUE THREAD

**Issue by geospatialem** [bmcbride/bootleaf#18]
When hitting 'enter' while in the search box the map will re-load as if the user refreshes the page, even if results are displayed in the search box.

The enhancement could include either a zoom to the top search result, no functionality (disable the re-load), or additional options.

![untitled](https://cloud.githubusercontent.com/assets/5023024/5766578/5abf5a7c-9cc8-11e4-9cf8-1e71e24af425.png)

**Comment by bmcbride** [comment]
Thanks for catching this @geospatialem!

**Comment by geospatialem** [comment]
Awesome, thanks @bmcbride!! :-)
