### ISSUE TITLE
Lengthy content in .navbar-brand obscures layer selector on mobile devices

### ISSUE THREAD

**Issue by skorasaurus** [bmcbride/bootleaf#19]
Hi Bryan, 

Thanks for your effort and time in making bootleaf. 

Making a lengthy title on the main page will result in the layer selector to be partially obscured on some mobile devices. 

I first encountered this on my Samsung S5, Android [4.4.4.], firefox  35;  also on Chrome 40.0.2214.89 and included a screenshot below
I was also able to reproduce it for a few other mobile devices using the Developer Tools on Chrome. 

A reproducible example, which uses the latest release from master is, at http://skorasaurus.github.io/bootleaf  

![pushbullet](https://cloud.githubusercontent.com/assets/955351/6114619/60967774-b06d-11e4-9df6-05f2eef50e55.png)

**Comment by bmcbride** [comment]
You'd have to tweak the font-size for the navbar-brand class in the CSS media queries. See https://github.com/bmcbride/bootleaf/blob/master/assets/css/app.css#L147. Looks like changing it to 12px or thereabouts might work.

```
@media (max-width: 992px) {
  .navbar .navbar-brand {
    font-size: 12px;
  }
}
```

**Comment by skorasaurus** [comment]
Thanks for the simple fix!

**Comment by bmcbride** [comment]
You're welcome!
