### ISSUE TITLE
Windows Phone 8.1 IE screen rotation intermittent glitch

### ISSUE THREAD

**Issue by pasho** [bmcbride/bootleaf#22]
Hi,

I've found an interesting problem with Bootleaf rendering on WP8.1 IE. Sometimes when I rotate the screen from portrait to landscape part of the screen doesn't get rendered. It happens approximately once out of three times. Refresh helps.

![wp_ss_20150524_0001](https://cloud.githubusercontent.com/assets/425689/7789600/253cea2a-025f-11e5-8978-d96ba0aa4ee8.jpg)

I've tested it on other browsers and other devices - works like charm. Freaking mobile IE!
Tried to workaround it myself - forcing to redraw the #container element - no luck. 

I guess it's more a bug report for the Microsoft folks.

**Comment by bmcbride** [comment]
Yeah, not really sure what I can do about this... What version of IE? Does this happen on all Bootstrap sites? Have you tried rotating from this example page: this: http://getbootstrap.com/examples/starter-template/?

**Comment by pasho** [comment]
Yep, it's happens with the plain bootstrap as well. IE11 WP8.1.

![wp_ss_20150526_0001](https://cloud.githubusercontent.com/assets/425689/7817756/0bdaf4c0-03cf-11e5-811f-56b8cf68ed44.jpg)

I've reported this problem to the MS support.
https://connect.microsoft.com/IE/feedback/CreateFeedbackForm.aspx?FeedbackFormConfigurationID=5534&FeedbackType=1

**Comment by bmcbride** [comment]
¯\_(ツ)_/¯
Closing for now.
