### ISSUE TITLE
Support for Right Sidebar

### ISSUE THREAD

**Issue by tdaubs** [bmcbride/bootleaf#25]
It would be great to see bootleaf offer an option for a right sidebar.

**Comment by stefanocudini** [comment]
+1

**Comment by stefanocudini** [comment]
maybe a moore useful feature is.. double panel, right and left at same time

**Comment by bmcbride** [comment]
```
#sidebar {
  float: right;
}
```
And replace `fa-chevron-left` with `fa-chevron-right` in index.html. If you need anything more complex, you might want to check out https://github.com/turbo87/sidebar-v2/.

**Comment by jamesinealing** [comment]
Opened, resolved and closed before I could even say ... that's essentially what I did on http://postcodepast.com/ (work in progress)

**Comment by tdaubs** [comment]
Nice! Thanks!
