### ISSUE TITLE
Display Error in Chrome

### ISSUE THREAD

**Issue by keshwest** [bmcbride/bootleaf#26]
Hi Mr McBride

I have been having some issues displaying the GEOJSON's in Google chrome. When I open the page the loading bar displays over the map and the GEOJSON's fail to display, in addition the lists are not searchable as it appears not to be reading any of the GEOJSON content. It works perfectly in Firefox but I would like to be able to use it on other web browsers, eventually in an offline networked environment pointing to an map server.

I would greatly appreciate any advice you may have.

Thank you!!

Kesh

**Comment by bmcbride** [comment]
Do you have a live link you can share for debugging? Are you getting any JavaScript errors in Chrome?

**Comment by keshwest** [comment]
Hi Mr Mcbride
I have been working to correct this problem for a while and the day after i message you I find information as detailed in the link below. I now have it working, I apologise for my preemptive query. 
Thank you  for your time and quick response.
https://code.google.com/p/chromium/issues/detail?id=40787

Cheers 
Kesh!

Date: Sat, 27 Jun 2015 06:08:08 -0700

**Comment by bmcbride** [comment]
Good to hear!
