### ISSUE TITLE
Search and map layers not displaying

### ISSUE THREAD

**Issue by cartochris** [bmcbride/bootleaf#28]
Hi there

I downloaded the zip file and unzipped it onto my web server but am having some problems as I cannot seem to be able to retrieve results from the search box or add the map layers.

I tried saving all of the externally referenced css and js files to my local server but this didn't help, not sure if there are any settings I need to alter at all after downloading and unzipping the zip file?

Thanks

**Comment by bmcbride** [comment]
Are you getting any console errors? It sounds like it could potentially be a CORS same-origin issue.

**Comment by cartochris** [comment]
No errors that I'm aware of - I am not familiar with CORS, does that relate to settings that I may need to alter on my web server?

**Comment by bmcbride** [comment]
It's hard to troubleshoot from here, but it sounds like the browser cannot access the geojson resources. What browser and web server are you using? If it's IIS, it may be blocking the geojson files... I think I've seen that before.

**Comment by cartochris** [comment]
Yes I am using IIS and have tried Google Chrome and IE. So I should try to add the geojson extension as a new MIME type on the server?

**Comment by bmcbride** [comment]
Yeah, you might also try just changing the extension to .txt (be sure to update the references in the assets/js/app.js file as well).

**Comment by cartochris** [comment]
I will try that, thanks
