### ISSUE TITLE
animation not working

### ISSUE THREAD

**Issue by KrishnaPG** [bmcbride/bootleaf#32]
The sidebar display animation is not working correctly. The css says "ease-transition", but the sidebar does not look like respecting that. Tried changing that transition duration to 10 sec (just for testing), no change in the animation - it hides/shows abruptly.

Here is an example of what I am after: http://ironsummitmedia.github.io/startbootstrap-simple-sidebar/

**Comment by bmcbride** [comment]
Closed by #40
