### ISSUE TITLE
How to stack the sidebar below the map in mobile display

### ISSUE THREAD

**Issue by KrishnaPG** [bmcbride/bootleaf#33]
In the portrait devices, the height is more than width, which makes the sidebar good to go "below" the map (stacked vertically) rather than share the same small horizontal width.

How to achieve this effect with this template/theme? I tried making the sidebar and map asas col-xs-12 (and col-md-8 and col-md-4) - but it did not work.

It would be great if you could provide a way to achieve this. Essentially I would like to have the map take 100% of width on the small screen and below it (somewhere around 50% of the height) the sidebar should start displaying its content in a scrollable view

**Comment by bmcbride** [comment]
This is out of the scope of this template. Feel free to fork and modify as needed.
