### ISSUE TITLE
Geojson Formatting

### ISSUE THREAD

**Issue by remmi11** [bmcbride/bootleaf#37]
Not an issue. Just a question. I am getting invalid geojson errors in the console while trying to implement my own data via app.js.  I was wondering where your geojson was created to try to match the formatting?

**Comment by bmcbride** [comment]
Try: http://geojson.io or http://geojsonlint.com/.

**Comment by remmi11** [comment]
Thank you! I love your projects by the way!

**Comment by bmcbride** [comment]
No problem and thanks for the kind words!
