### ISSUE TITLE
Geojsons are not displayed in demo

### ISSUE THREAD

**Issue by schaeferlea** [bmcbride/bootleaf#43]
Hello, 
I am quite impressed by this combination of bootstrap and leaflet! I really want to use it for a little project. But I am having difficulties with the downloaded version: it doesn't show the Geojsons (Museums, Theaters, Boroughs and Subways) – They don't appear in the downloaded version. And I am to new to js. to find the error by myself. 
So could you please check the data you gave for download? Thanks!

**Comment by bmcbride** [comment]
Thanks for the kind words! Make sure you are running it from a local webserver (localhost).

**Comment by schaeferlea** [comment]
Thank you! That was the problem ;)

**Comment by bmcbride** [comment]
Happy to help!
