### ISSUE TITLE
Cannot change startup position

### ISSUE THREAD

**Issue by dfaustryjak** [bmcbride/bootleaf#45]
map = L.map("map", {
  zoom: 20,
  center: [10.702222, -73.979378],
  layers: [cartoLight, boroughs, markerClusters, highlight],
  zoomControl: false,
  attributionControl: false,

});

I just change numbers between brackets and I didn't saw any results

**Comment by spatialhast** [comment]
comment this row https://github.com/bmcbride/bootleaf/blob/master/assets/js/app.js#L455

**Comment by bmcbride** [comment]
@spatialhast is correct. That line fits the map to the boroughs layer bounds after everything has been loaded.
