### ISSUE TITLE
Bootleaf & GpPluginLeaflet-src.js

### ISSUE THREAD

**Issue by limace2000** [bmcbride/bootleaf#48]
Hello

I like bootleaf and this plugin  GpPluginLeaflet-src.js
With this we can play on order and opacity of each layer
![layer](https://user-images.githubusercontent.com/16049520/29583118-54c32d5c-877f-11e7-8965-79b64e4ffe5d.png)

I try to use this on bootleaf without success, have you an idea ?
[http://www.test.pyrenees-refuges.com/leaflet/bootleaf-master/](url)

Thanks

**Comment by bmcbride** [comment]
This is outside the scope of this template.
