### ISSUE TITLE
Low Performance +10k Markers

### ISSUE THREAD

**Issue by AusPrinzip** [bmcbride/bootleaf#51]
Anyone tried loading more than 10k markers?

The whole map behaviour is clumsy and/or crashes. Initially I tought it was due to load time (6mb geojson), but after reduzing size to its tenth by gzip compressing im still experiencing clumsy behaviour.

Is it possible that the sidebar is responsible for the browser to crash when loading tons of markers? Often markers are visibly loaded and just as I move the map somewhere else, sidebar starts doing the sync. So I though it might be useful getting rid of the sidebar for testing.

Any insights?

**Comment by bmcbride** [comment]
You are definitely likely to run into performance issues trying to display that many features client-side! Marker clustering helps with the map, but loading that many DOM items in the sidebar is likely going to crash the browser. You may be better off trying to implement some server-side solution and somehow limiting the sidebar items.
