### ISSUE TITLE
Incompatibility with Leaflet-easyPrint plugin 

### ISSUE THREAD

**Issue by abrobia** [bmcbride/bootleaf#55]
When adding the Leaflet-easyPrint plugin using the Bootleaf template, the Print icon control appears on the map but doesn't react. I tested Leaflet-easyPrint plugin without using Bootleaf and it works well. Somebody knows how to fix?
Thanks

**Comment by gavinharriss** [comment]
Do you have a ready-to-go example code of issue I can take a look at?

**Comment by abrobia** [comment]
Unfortunately, I don't have a ready-to-go example code. I try to give a more detailed issue:
the console is showing the following TypeError: window.print is not a function. 
Specifying the next: 
printPage: http://localhost/[...]leaflet.easyPrint.js:36:2
h: https://unpkg.com/leaflet@1.0.3/dist/leaflet.js:6:11428

Hope this explanation should be useful/enough.  Grateful for your interest

**Comment by abrobia** [comment]
I have solved the problem as indicated in the following link: https://stackoverflow.com/questions/14383733/javascript-window-print-not-recognizing-window-object 

The problem was the name of the variable. The variable cannot be named as "print" due to a conflict between element IDs. Once changed the variable name, the plugin works.
