### ISSUE TITLE
searchpush for line features

### ISSUE THREAD

**Issue by ghost** [bmcbride/bootleaf#59]
Hi,
I'm a rookie in programming and I'm really grateful for this template. I have noticed that the search features work only for polygon and point geojson. Kindly advice on how to enable search for line geojson features?

**Comment by anshori** [comment]
Hi @innchy , you can refer to my app.js file but this file extension I changed to txt to be get attach.
** Change app.txt to app.js

[app.txt](https://github.com/bmcbride/bootleaf/files/2124224/app.txt)

**Comment by ghost** [comment]
Hi @anshori ,

I'm eternally grateful. This worked like a charm.

A million thanks.
